id: P004511
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4807
  title: སྤྱོད་འཇུག་གི་འགྲེལ་བཤད་རྒྱལ་སྲས་ཡོན་ཏན་བུམ་བཟང་།
  author: ''
  volumes:
    2523dd30d9094c80a92d7f604ba03b18:
      image_group_id: I3CN4809
      title: ''
      volume_number: 1
      total_pages: 846
      base_file: v001.txt
