id: P004511
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:28:28.915056
source_metadata:
  id: bdr:W3CN4807
  title: སྤྱོད་འཇུག་གི་འགྲེལ་བཤད་རྒྱལ་སྲས་ཡོན་ཏན་བུམ་བཟང་།
  author: ''
  volumes:
    2523dd30d9094c80a92d7f604ba03b18:
      image_group_id: I3CN4809
      title: ''
      volume_number: 1
      total_pages: 846
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
